version: '1.0'

# 컴퓨터들
services:

  # 컴퓨터이름
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
      # - ./src:myfolder/src
    ports:
      - 3000:3000

  # 컴퓨터이름
  database:
    image: mongo:5
    ports:
      - 27017:27017
