version: '1.0'

# 컴퓨터들
services:

  # 컴퓨터이름
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  # 컴퓨터이름
  database:
    image: mongo:5
    # ports:
    #   - 27017:27017 => 주석처리 시 mongoDB compass접속 불가
    #                 => 하지만, 네임리졸루션으로 express에서는 접속됨
