version: '3.7'

# 컴퓨터들
services:

  # 컴퓨터이름
  backend:
    image: asia.gcr.io/linear-reporter-437203-g8/backend-project-nestjs:0.2
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod

  # 컴퓨터이름
  # database:
  #   # platform: linux/86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: "mydocker"
  #     MYSQL_ROOT_PASSWORD: "root"
  #   ports:
  #     - 3306:3306

